# Generated by Django 4.2.27 on 2026-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(help_text='Titre principal affiché sur la bannière', max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Sous-titre ou description courte', null=True, verbose_name='Description')),
                ('image', models.ImageField(help_text='Image de fond de la bannière (recommandé: 1920x800px)', upload_to='hero_banners/', verbose_name='Image de fond')),
                ('bouton_texte', models.CharField(blank=True, default='Découvrir nos services', max_length=100, null=True, verbose_name='Texte du bouton')),
                ('bouton_lien', models.CharField(blank=True, default='/services', help_text='URL vers laquelle le bouton redirige (ex: /services, /contact)', max_length=255, null=True, verbose_name='Lien du bouton')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Les bannières sont affichées par ordre croissant', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour masquer cette bannière', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bannière Hero',
                'verbose_name_plural': 'Bannières Hero',
                'db_table': 'hero_banners',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
