# Generated by Django 4.2.29 on 2026-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='bouton_lien',
            field=models.CharField(blank=True, default='https://shoemaker.cireur.test-vps-online.xyz/fr/services', help_text='URL complète vers laquelle le bouton redirige', max_length=255, null=True, verbose_name='Lien du bouton'),
        ),
    ]
