# Generated by Django 4.2.27 on 2025-12-26 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code unique')),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
            ],
            options={
                'verbose_name': 'Code de collecte',
                'verbose_name_plural': 'Codes de Collecte',
                'db_table': 'codes_collecte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(help_text='Code unique (ex: NOEL2025)', max_length=50, unique=True, verbose_name='Code promo')),
                ('type_reduction', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], max_length=20, verbose_name='Type de réduction')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 20 pour 20%) ou montant fixe (ex: 50.00)', max_digits=10, verbose_name='Valeur')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes Promo',
                'db_table': 'codes_promo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code_unique', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Code commande')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('montant_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant réduction')),
                ('montant_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant final')),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut paiement')),
                ('statut_commande', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('confirmee', 'Confirmée'), ('en_collecte', 'En collecte'), ('collectee', 'Collectée'), ('en_cours', 'En cours'), ('prete', 'Prête'), ('en_livraison', 'En livraison'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20, verbose_name='Statut commande')),
                ('date_assignation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation collecte")),
                ('date_confirmation_livreur', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation livreur collecte')),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='Rappel 1h avant envoyé')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('date_assignation_livraison', models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation livraison")),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('adresse_collecte', models.TextField(verbose_name='Adresse de collecte')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('telephone_collecte', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_collecte', models.DateField(verbose_name='Date de collecte')),
                ('creneau_horaire', models.CharField(max_length=50, verbose_name='Créneau horaire')),
                ('note_collecte', models.TextField(blank=True, null=True, verbose_name='Note collecte')),
                ('code_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='commande.codepromo', verbose_name='Code promo')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('description', models.TextField(verbose_name='Description')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur')),
                ('photo', models.ImageField(upload_to='commandes/produits/%Y/%m/', verbose_name='Photo')),
                ('note_utilisateur', models.TextField(blank=True, null=True, verbose_name='Note utilisateur')),
                ('code_collecte', models.CharField(blank=True, help_text='Code unique collé sur la paire de chaussures', max_length=20, null=True, verbose_name='Code de collecte')),
                ('date_collecte_effective', models.DateTimeField(blank=True, help_text='Date à laquelle le code a été assigné et la paire collectée', null=True, verbose_name='Date de collecte effective')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix HT')),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='TVA (%)')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TTC')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='commande.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Produit de commande',
                'verbose_name_plural': 'Produits de Commande',
                'db_table': 'commande_produits',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code unique (ex: carte, especes, paypal)', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('icone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de Paiement',
                'db_table': 'moyens_paiement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('type_email', models.CharField(choices=[('nouvelle_commande_admin', 'Nouvelle commande (Admin)'), ('confirmation_commande_client', 'Confirmation commande (Client)'), ('assignation_livreur', 'Assignation livreur'), ('en_attente_collecte', 'En attente de collecte (Client)'), ('rappel_collecte', 'Rappel collecte (Client)'), ('confirmation_livreur_admin', 'Confirmation livreur (Admin)'), ('collecte_effectuee_client', 'Collecte effectuée (Client)'), ('collecte_effectuee_admin', 'Collecte effectuée (Admin)'), ('arrivee_atelier', 'Arrivée atelier (Client)'), ('assignation_livreur_livraison', 'Assignation livreur livraison'), ('livraison_effectuee_client', 'Livraison effectuée (Client)'), ('livraison_effectuee_admin', 'Livraison effectuée (Admin)'), ('contact_form', 'Formulaire de contact')], max_length=50, verbose_name="Type d'email")),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('contenu_html', models.TextField(verbose_name='Contenu HTML')),
                ('contenu_text', models.TextField(verbose_name='Contenu texte')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_logs', to='commande.commande', verbose_name='Commande associée')),
            ],
            options={
                'verbose_name': 'Log Email',
                'verbose_name_plural': 'Logs Emails',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandeProduitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('nom_service', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HT')),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix TTC')),
                ('commande_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='commande.commandeproduit', verbose_name='Produit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_services', to='service.service', verbose_name='Service (référence)')),
            ],
            options={
                'verbose_name': 'Service de produit',
                'verbose_name_plural': 'Services de Produit',
                'db_table': 'commande_produit_services',
                'ordering': ['created_at'],
            },
        ),
    ]
