# Generated by Django 4.2.27 on 2025-12-26 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_collecte', to='users.deliveryperson', verbose_name='Livreur collecte'),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_person_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_livraison', to='users.deliveryperson', verbose_name='Livreur livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='moyen_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commande.moyenpaiement', verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='codecollecte',
            name='commande_produit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_collecte_obj', to='commande.commandeproduit', verbose_name='Produit associé'),
        ),
        migrations.AddField(
            model_name='codecollecte',
            name='genere_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['type_email'], name='email_logs_type_em_b70298_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['statut'], name='email_logs_statut_fa7dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['destinataire'], name='email_logs_destina_7295f9_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='email_logs_created_76afc3_idx'),
        ),
        migrations.AddIndex(
            model_name='codecollecte',
            index=models.Index(fields=['code'], name='codes_colle_code_3fe0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='codecollecte',
            index=models.Index(fields=['utilise'], name='codes_colle_utilise_69d2d9_idx'),
        ),
    ]
