# Generated by Django 4.2.27 on 2025-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepromo',
            name='montant_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum de commande pour appliquer le code promo (laisser vide pour aucun minimum)', max_digits=10, null=True, verbose_name='Montant minimum'),
        ),
        migrations.AddField(
            model_name='codepromo',
            name='utilisation_max',
            field=models.IntegerField(blank=True, help_text="Nombre maximum d'utilisations par client (laisser vide pour illimité)", null=True, verbose_name='Utilisations maximales par client'),
        ),
    ]
