# Generated by Django 4.2.27 on 2025-12-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneaux', '0001_initial'),
        ('commande', '0003_add_code_promo_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='creneau',
            field=models.ForeignKey(blank=True, help_text='Créneau horaire sélectionné (si système de créneaux activé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='creneaux.creneaux', verbose_name='Créneau'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='creneau_horaire',
            field=models.CharField(help_text='Horaire en texte (rempli automatiquement depuis le créneau ou manuellement si système désactivé)', max_length=50, verbose_name='Créneau horaire'),
        ),
    ]
