# Generated by Django 4.2.27 on 2025-12-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_add_modification_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='type_email',
            field=models.CharField(choices=[('nouvelle_commande_admin', 'Nouvelle commande (Admin)'), ('confirmation_commande_client', 'Confirmation commande (Client)'), ('modification_commande_client', 'Modification commande (Client)'), ('assignation_livreur', 'Assignation livreur'), ('desassignation_livreur', 'Désassignation livreur'), ('en_attente_collecte', 'En attente de collecte (Client)'), ('rappel_collecte', 'Rappel collecte (Client)'), ('confirmation_livreur_admin', 'Confirmation livreur (Admin)'), ('collecte_effectuee_client', 'Collecte effectuée (Client)'), ('collecte_effectuee_admin', 'Collecte effectuée (Admin)'), ('arrivee_atelier', 'Arrivée atelier (Client)'), ('assignation_livreur_livraison', 'Assignation livreur livraison'), ('livraison_effectuee_client', 'Livraison effectuée (Client)'), ('livraison_effectuee_admin', 'Livraison effectuée (Admin)'), ('contact_form', 'Formulaire de contact')], max_length=50, verbose_name="Type d'email"),
        ),
    ]
