# Generated by Django 4.2.27 on 2026-01-13 15:49

from django.db import migrations, models


def update_confirmee_to_nouvelle(apps, schema_editor):
    """
    Mise à jour de toutes les commandes avec statut 'confirmee' vers 'nouvelle'
    """
    Commande = apps.get_model('commande', 'Commande')
    Commande.objects.filter(statut_commande='confirmee').update(statut_commande='nouvelle')


def reverse_update(apps, schema_editor):
    """
    Fonction inverse (ne fait rien car on ne peut pas deviner quel était le statut d'origine)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_add_default_payment_methods'),
    ]

    operations = [
        # Étape 1: Mettre à jour les données existantes
        migrations.RunPython(update_confirmee_to_nouvelle, reverse_update),

        # Étape 2: Modifier le champ pour retirer 'confirmee' des choix
        migrations.AlterField(
            model_name='commande',
            name='statut_commande',
            field=models.CharField(
                choices=[
                    ('nouvelle', 'Nouvelle'),
                    ('en_collecte', 'En collecte'),
                    ('collectee', 'Collectée'),
                    ('en_cours', 'En cours'),
                    ('prete', 'Prête'),
                    ('en_livraison', 'En livraison'),
                    ('terminee', 'Terminée'),
                    ('annulee', 'Annulée')
                ],
                default='nouvelle',
                max_length=20,
                verbose_name='Statut commande'
            ),
        ),
    ]
