# Generated by Django 4.2.27 on 2026-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_remove_confirmee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepromo',
            name='utilisation_max',
            field=models.IntegerField(blank=True, help_text="Nombre maximum total d'utilisations du code promo (tous clients confondus, laisser vide pour illimité)", null=True, verbose_name="Nombre maximum d'utilisations"),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='type_email',
            field=models.CharField(choices=[('nouvelle_commande_admin', 'Nouvelle commande (Admin)'), ('confirmation_commande_client', 'Confirmation commande (Client)'), ('modification_commande_client', 'Modification commande (Client)'), ('assignation_livreur', 'Assignation livreur'), ('desassignation_livreur', 'Désassignation livreur'), ('en_attente_collecte', 'En attente de collecte (Client)'), ('rappel_collecte', 'Rappel collecte (Client)'), ('confirmation_livreur_admin', 'Confirmation livreur (Admin)'), ('collecte_effectuee_client', 'Collecte effectuée (Client)'), ('collecte_effectuee_admin', 'Collecte effectuée (Admin)'), ('arrivee_atelier', 'Arrivée atelier (Client)'), ('assignation_livreur_livraison', 'Assignation livreur livraison'), ('confirmation_livraison_client', 'Confirmation livraison (Client)'), ('confirmation_livraison_admin', 'Confirmation livraison (Admin)'), ('livraison_effectuee_client', 'Livraison effectuée (Client)'), ('livraison_effectuee_admin', 'Livraison effectuée (Admin)'), ('contact_form', 'Formulaire de contact')], max_length=50, verbose_name="Type d'email"),
        ),
    ]
