# Generated by Django 4.2.27 on 2026-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_add_livraison_confirmation_email_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_confirmation_livraison',
            field=models.CharField(blank=True, help_text='Code unique généré lors de la confirmation de livraison par le livreur', max_length=10, null=True, verbose_name='Code de confirmation livraison'),
        ),
    ]
