# Generated by Django 4.2.27 on 2026-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_add_code_confirmation_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepromo',
            name='max_uses_per_user',
            field=models.IntegerField(blank=True, help_text="Nombre maximum d'utilisations par utilisateur (laisser vide pour illimité)", null=True, verbose_name='Utilisations max par personne'),
        ),
    ]
