# Generated by Django 4.2.27 on 2026-01-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0011_add_max_uses_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='monnaie_collecte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de monnaie remis au livreur pour la collecte', max_digits=10, null=True, verbose_name='Monnaie collecte'),
        ),
    ]
