# Generated by Django 4.2.29 on 2026-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Administrator'), ('SUPERADMIN', 'Super Administrator')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
