# Generated by Django 4.2.27 on 2025-12-26 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix_minimum_ht', models.DecimalField(decimal_places=2, help_text='Prix minimum hors taxe', max_digits=10, verbose_name='Prix minimum HT')),
                ('tva', models.DecimalField(decimal_places=2, help_text='Taux de TVA en pourcentage (ex: 20.00 pour 20%)', max_digits=5, verbose_name='TVA (%)')),
                ('prix_minimum_ttc', models.DecimalField(blank=True, decimal_places=2, help_text='Prix minimum toutes taxes comprises', max_digits=10, null=True, verbose_name='Prix minimum TTC')),
                ('delai_minimum_jours', models.IntegerField(help_text='Délai minimum en jours', verbose_name='Délai minimum (jours)')),
                ('delai_maximum_jours', models.IntegerField(blank=True, help_text='Délai maximum en jours (optionnel)', null=True, verbose_name='Délai maximum (jours)')),
                ('nombre_heures_delai_maximum', models.IntegerField(help_text='Heures calculées depuis delai_max ou delai_min', verbose_name="Nombre d'heures (délai maximum)")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('brouillon', 'Brouillon')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('icone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services de Réparation',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
    ]
