# Generated by Django 4.2.27 on 2026-01-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_add_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image représentative de la catégorie (recommandé: 800x600px)', null=True, upload_to='categories/', verbose_name='Image de la catégorie'),
        ),
    ]
