# Generated by Django 4.2.29 on 2026-04-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('AUTRE', 'Autre')], db_index=True, max_length=10)),
                ('recherche', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('TOUS', 'Tous')], default='TOUS', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Bénin', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('age_min', models.PositiveSmallIntegerField(default=18)),
                ('age_max', models.PositiveSmallIntegerField(default=50)),
                ('distance_max', models.PositiveIntegerField(default=50, help_text='km')),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='profils/photos/')),
                ('video_presentation', models.FileField(blank=True, null=True, upload_to='profils/videos/')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu'), ('BANNI', 'Banni')], db_index=True, default='ACTIF', max_length=15)),
                ('est_verifie', models.BooleanField(default=False)),
                ('est_en_ligne', models.BooleanField(db_index=True, default=False)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'db_table': 'profils',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='profils/photos/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('est_principale', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profil.profil')),
            ],
            options={
                'verbose_name': 'Photo de profil',
                'verbose_name_plural': 'Photos de profil',
                'db_table': 'photos_profil',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddIndex(
            model_name='profil',
            index=models.Index(fields=['genre', 'recherche', 'statut'], name='profils_genre_cf9028_idx'),
        ),
        migrations.AddIndex(
            model_name='profil',
            index=models.Index(fields=['statut', 'est_en_ligne'], name='profils_statut_f5d30b_idx'),
        ),
    ]
