# Generated by Django 4.2.27 on 2025-12-26 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(help_text='Nom complet du client qui témoigne', max_length=255, verbose_name='Nom du client')),
                ('profession', models.CharField(blank=True, help_text='Profession ou titre du client', max_length=255, verbose_name='Profession')),
                ('description', models.TextField(help_text='Contenu du témoignage du client', verbose_name='Témoignage')),
                ('photo', models.ImageField(blank=True, help_text='Photo du client (optionnel)', null=True, upload_to='temoignages/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'db_table': 'temoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
