# Generated by Django 4.2.29 on 2026-04-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(help_text='Ex: gratuit, premium, vip', unique=True)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prix_affiche', models.CharField(help_text='Ex: "14,99€ / mois"', max_length=50)),
                ('duree', models.CharField(help_text='Ex: "Mensuel", "À vie"', max_length=50)),
                ('fonctionnalites', models.JSONField(default=list)),
                ('fonctionnalites_exclues', models.JSONField(default=list)),
                ('est_populaire', models.BooleanField(default=False)),
                ('icone', models.CharField(choices=[('heart', 'Heart'), ('star', 'Star'), ('crown', 'Crown')], default='heart', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'db_table': 'plans_abonnement',
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nombre_mois', models.PositiveIntegerField(default=1)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('code_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes internes (admin)', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='souscriptions', to='abonnement.planabonnement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Souscription',
                'verbose_name_plural': 'Souscriptions',
                'db_table': 'souscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'statut'], name='souscriptio_user_id_ce9f0f_idx')],
            },
        ),
    ]
