# Generated by Django 4.2.27 on 2025-12-26 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code_devis', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Code devis')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('informations_supplementaires', models.TextField(blank=True, null=True, verbose_name='Informations supplémentaires')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('envoye', 'Devis envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('montant_total_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total HT')),
                ('montant_total_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total TTC')),
                ('message_admin', models.TextField(blank=True, null=True, verbose_name="Message de l'admin")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('type_chaussure', models.CharField(max_length=100, verbose_name='Type')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='devis/produits/%Y/%m/', verbose_name='Photo')),
                ('services_souhaites', models.JSONField(default=list, help_text='Liste des services: reparation, nettoyage_complet, teinture', verbose_name='Services souhaités')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description/État')),
                ('prix_unitaire_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire HT')),
                ('prix_unitaire_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire TTC')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='devis.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Produit de devis',
                'verbose_name_plural': 'Produits de Devis',
                'db_table': 'devis_produits',
                'ordering': ['created_at'],
            },
        ),
    ]
