# Generated by Django 4.2.27 on 2026-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devisproduit',
            name='services_souhaites',
            field=models.JSONField(default=list, help_text='Liste des UUIDs des services sélectionnés (référence au modèle Service)', verbose_name='Services souhaités'),
        ),
    ]
