# Generated by Django 4.2.27 on 2026-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='emails_destinataires_contact',
            field=models.JSONField(default=list, help_text='Liste des adresses email qui recevront les notifications de formulaire de contact', verbose_name='Emails destinataires des formulaires de contact'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='url_site',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du site web'),
        ),
    ]
