# Generated by Django 4.2.27 on 2025-12-26 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('actif', models.BooleanField(default=True, help_text='Si désactivé, les clients peuvent saisir un créneau horaire en texte libre sans sélectionner un créneau prédéfini', verbose_name='Système de créneaux actif')),
                ('message_desactivation', models.TextField(blank=True, help_text='Message affiché aux clients quand le système de créneaux est désactivé (optionnel)', null=True, verbose_name='Message lors de la désactivation')),
            ],
            options={
                'verbose_name': 'Configuration des créneaux',
                'verbose_name_plural': 'Configuration des créneaux',
                'db_table': 'creneaux_config',
            },
        ),
        migrations.CreateModel(
            name='Creneaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('date', models.DateField(help_text='Date du créneau', verbose_name='Date du créneau')),
                ('heure_debut', models.TimeField(help_text='Heure de début du créneau (ex: 09:00)', verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du créneau (ex: 12:00)', verbose_name='Heure de fin')),
                ('duree_limite_minutes', models.IntegerField(default=30, help_text='Durée limite avant le début du créneau (en minutes). Le créneau devient indisponible une fois cette durée atteinte.', verbose_name='Durée limite (minutes)')),
                ('capacite_max', models.IntegerField(default=10, help_text='Nombre maximum de réservations autorisées pour ce créneau', verbose_name='Capacité maximale')),
                ('reservations_actuelles', models.IntegerField(default=0, help_text='Nombre de réservations actuelles pour ce créneau', verbose_name='Réservations actuelles')),
                ('actif', models.BooleanField(default=True, help_text="Si False, le créneau n'est plus disponible pour les réservations", verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'db_table': 'creneaux',
                'ordering': ['date', 'heure_debut'],
                'indexes': [models.Index(fields=['date', 'actif'], name='creneaux_date_94e09a_idx'), models.Index(fields=['date', 'heure_debut'], name='creneaux_date_116eb2_idx')],
                'unique_together': {('date', 'heure_debut', 'heure_fin')},
            },
        ),
    ]
